### PR TITLE
Fix PermissionsViewer not showing role names.

### PR DESCRIPTION
**Pull request by ShaneMcC**
Looks like `guild.roles` is no longer always populated.

### CODE REVIEW

**Comment by ShaneMcC** [comment]
This will resolve #758, #757, #755 and #754

**Comment by JustOptimize** [comment]
Been using this version for a while now, it's stable and has no issues, how much longer do we need to wait to get this merged to main? @rauenzi

**Comment by XxUnkn0wnxX** [comment]
+4 months and still not merged, maybe he has abandoned the plugin?

**Comment by zerebos** [comment]
In the future, please only modify the source files and not the packed version.

**Comment by ShaneMcC** [comment]
Thanks for merging.

I modified the packed version as well because that seemed to be how all your other commits were. I'll remember for future if it's needed again.

**Comment by zerebos** [comment]
I get how that can be confusing since I tend to do it all in one go. But committing the packed version triggers an update sequence with the BetterDiscord website, and that's something I only want to do after all the fixes are in

**Comment by ShaneMcC** [comment]
Makes sense, noted.

**Pull request closed without merging**
